import "./some_module.ts"
import "./test_meta"
import "./test_path"
import "./test_fs_promises"
import "./test_imp_fs"
import "../time/index"
import "../parsers/index"
import "../clap/smoke"
import "../clap/test_clap_types"
import "../url/index"
import "../fs/index"
import "../fetch/index"
import "../rs_string/index"
import "../subprocess/index.ts"
import "../encoding/index.ts"
import "../env/index.ts"
import "../hash/index.ts"
import "../process/test_process"
import "../signal/test_signal"
import "../crypto/index.ts"

console.log("ALL SMOKE TESTS PASSED")
